### ISSUE TITLE
Exceeded rate limit

### ISSUE THREAD

**Issue by kevadamson** [bymayo/dribbble#3]
Will wrapping the tags in `{% cache %}` solve this? For example:

```
{% cache for 12 hours %}

  {% set shots = craft.dribbble.get('user/shots', 180) %}
  {% set shots = shuffle(shots) %}

  {% for shot in shots|slice(0,3) %}
    {{ shot.title }}
  {% endfor %}

{% endcache %}
```

**Comment by bymayo** [comment]
That should work, as it won't be making a request every time the page loads.

But I have a feeling you also might be hitting your limit due to how many shots you're getting. 

The limits seem to be:

```
you can make up to 60 requests per minute and 1,440 requests per day per authenticated user. For unauthenticated requests using your application’s client access token, you can make up to 60 requests per minute and 10,000 requests per day.
```

So I would limit your initial `get` to just 60 requests to make sure you don't hit a limit straight away.

**Comment by kevadamson** [comment]
Ah right. Thanks for the heads up :)
